Repository ixm-one/ixm, pull requests merged in 2025-03, with the labels that each got.

#22 fix(docs): improve light theme contrast for code blocks
  .vitepress/ixm/theme.js
  .vitepress/theme/custom.css
Labels: category:bug, subject:docs, docs:style

#26 refactor(cmake)!: rename `internal` -> `runtime`
  CMakeLists.txt
  runtime/check.cmake
  runtime/common.cmake
  runtime/features.cmake
  runtime/find.cmake
  runtime/package.cmake
  runtime/policies.cmake
  runtime/protobuf.cmake
  runtime/supports.cmake
  runtime/validate.cmake
Labels: subject:modules

#27 feat(cmake): enhance internal unicode + hyperlink detection for running under cmake-gui
  runtime/supports.cmake
Labels: subject:modules, category:enhancement
